package ui;

import model.Pet;
import model.PetType;
import model.species.Dog;
import model.species.Hamster;
import ui.art.atlas.*;


public class ConsoleArtRender {

    public void ConsoleArtRender(UiScene uiScene, Pet pet) {
        String[] art = pickArt(uiScene, pet.getType());
        for (String line : art) {
            System.out.println(line);
        }
        System.out.println();
    }

    private String[] pickArt(UiScene uiScene, PetType type) {
        return switch (type) {
            case BUNNY -> switch (uiScene) {
                case IDLE -> BunnyArt.IDLE;
                case PLAY -> BunnyArt.PLAY;
                case FEED -> BunnyArt.FEED;
                case SLEEP -> BunnyArt.SLEEP;
                case WAKE -> BunnyArt.IDLE;
                case SICK -> BunnyArt.SICK;
                case HUNGRY ->  BunnyArt.HUNGRY;
                case TIRED -> BunnyArt.TIRED;
                case HEAL ->  BunnyArt.HEAL;
                case BOW ->  BunnyArt.BOW;
                case SCARF ->   BunnyArt.SCARF;
                case BATH ->  BunnyArt.BATH;
                case BATH_SCARF ->  BunnyArt.BATH_SCARF;
                case BATH_BOW ->  BunnyArt.BATH_BOW;
                case FEED_BOW ->   BunnyArt.FEED_BOW;
                case FEED_BATH ->    BunnyArt.FEED_BATH;
                case FEED_SCARF ->    BunnyArt.FEED_SCARF;
                case FEED_BATH_BOW ->     BunnyArt.FEED_BATH_BOW;
                case FEED_BATH_SCARF ->     BunnyArt.FEED_BATH_SCARF;
                case PLAY_BATH ->     BunnyArt.PLAY_BATH;
                case PLAY_SCARF ->    BunnyArt.PLAY_SCARF;
                case PLAY_BOW ->     BunnyArt.PLAY_BOW;
                case PLAY_BATH_BOW ->     BunnyArt.PLAY_BATH_BOW;
                case PLAY_BATH_SCARF ->     BunnyArt.PLAY_BATH_SCARF;
                case HEAL_BOW ->      BunnyArt.HEAL_BOW;
                case HEAL_SCARF ->    BunnyArt.HEAL_SCARF;
                case HEAL_BATH ->     BunnyArt.HEAL_BATH;
                case HEAL_BATH_BOW ->     BunnyArt.HEAL_BATH_BOW;
                case HEAL_BATH_SCARF ->     BunnyArt.HEAL_BATH_SCARF;
                case SICK_BOW ->    BunnyArt.SICK_BOW;
                case SICK_BATH ->   BunnyArt.SICK_BATH;
                case SICK_SCARF ->  BunnyArt.SICK_SCARF;
                case SICK_BATH_BOW ->   BunnyArt.SICK_BATH_BOW;
                case SICK_BATH_SCARF -> BunnyArt.SICK_BATH_SCARF;
                case SLEEP_BOW ->     BunnyArt.SLEEP_BOW;
                case SLEEP_SCARF ->   BunnyArt.SLEEP_SCARF;
                case SLEEP_BATH ->      BunnyArt.SLEEP_BATH;
                case SLEEP_BATH_BOW ->      BunnyArt.SLEEP_BATH_BOW;
                case SLEEP_BATH_SCARF ->     BunnyArt.SLEEP_BATH_SCARF;
                case HUNGRY_BOW ->      BunnyArt.HUNGRY_BOW;
                case HUNGRY_BATH ->       BunnyArt.HUNGRY_BATH;
                case HUNGRY_SCARF ->      BunnyArt.HUNGRY_SCARF;
                case HUNGRY_BATH_BOW ->      BunnyArt.HUNGRY_BATH_BOW;
                case HUNGRY_BATH_SCARF ->       BunnyArt.HUNGRY_BATH_SCARF;
                case TIRED_BOW ->      BunnyArt.TIRED_BOW;
                case TIRED_BATH ->      BunnyArt.TIRED_BATH;
                case TIRED_SCARF ->       BunnyArt.TIRED_SCARF;
                case TIRED_BATH_BOW ->       BunnyArt.TIRED_BATH_BOW;
                case TIRED_BATH_SCARF ->        BunnyArt.TIRED_BATH_SCARF;
            };
            case CAT -> switch (uiScene) {
                case IDLE -> CatArt.IDLE;
                case FEED -> CatArt.FEED;
                case PLAY -> CatArt.PLAY;
                case SLEEP -> CatArt.SLEEP;
                case WAKE -> CatArt.IDLE;
                case SICK -> CatArt.SICK;
                case HUNGRY -> CatArt.HUNGRY;
                case TIRED -> CatArt.TIRED;
                case HEAL ->  CatArt.HEAL;
                case BOW ->  CatArt.BOW;
                case SCARF ->  CatArt.SCARF;
                case BATH ->  CatArt.BATH;
                case BATH_SCARF ->  CatArt.BATH_SCARF;
                case BATH_BOW ->  CatArt.BATH_BOW;
                case FEED_BOW ->   CatArt.FEED_BOW;
                case FEED_BATH ->    CatArt.FEED_BATH;
                case FEED_SCARF ->    CatArt.FEED_SCARF;
                case FEED_BATH_BOW ->     CatArt.FEED_BATH_BOW;
                case FEED_BATH_SCARF ->     CatArt.FEED_BATH_SCARF;
                case PLAY_BATH ->     CatArt.PLAY_BATH;
                case PLAY_SCARF ->    CatArt.PLAY_SCARF;
                case PLAY_BOW ->     CatArt.PLAY_BOW;
                case PLAY_BATH_BOW ->     CatArt.PLAY_BATH_BOW;
                case PLAY_BATH_SCARF ->     CatArt.PLAY_BATH_SCARF;
                case HEAL_BOW ->      CatArt.HEAL_BOW;
                case HEAL_SCARF ->    CatArt.HEAL_SCARF;
                case HEAL_BATH ->     CatArt.HEAL_BATH;
                case HEAL_BATH_BOW ->     CatArt.HEAL_BATH_BOW;
                case HEAL_BATH_SCARF ->     CatArt.HEAL_BATH_SCARF;
                case SICK_BOW ->    CatArt.SICK_BOW;
                case SICK_BATH ->   CatArt.SICK_BATH;
                case SICK_SCARF ->  CatArt.SICK_SCARF;
                case SICK_BATH_BOW ->   CatArt.SICK_BATH_BOW;
                case SICK_BATH_SCARF -> CatArt.SICK_BATH_SCARF;
                case SLEEP_BOW ->     CatArt.SLEEP_BOW;
                case SLEEP_SCARF ->   CatArt.SLEEP_SCARF;
                case SLEEP_BATH ->      CatArt.SLEEP_BATH;
                case SLEEP_BATH_BOW ->      CatArt.SLEEP_BATH_BOW;
                case SLEEP_BATH_SCARF ->     CatArt.SLEEP_BATH_SCARF;
                case HUNGRY_BOW ->      CatArt.HUNGRY_BOW;
                case HUNGRY_BATH ->       CatArt.HUNGRY_BATH;
                case HUNGRY_SCARF ->      CatArt.HUNGRY_SCARF;
                case HUNGRY_BATH_BOW ->      CatArt.HUNGRY_BATH_BOW;
                case HUNGRY_BATH_SCARF ->       CatArt.HUNGRY_BATH_SCARF;
                case TIRED_BOW ->      CatArt.TIRED_BOW;
                case TIRED_BATH ->      CatArt.TIRED_BATH;
                case TIRED_SCARF ->       CatArt.TIRED_SCARF;
                case TIRED_BATH_BOW ->       CatArt.TIRED_BATH_BOW;
                case TIRED_BATH_SCARF ->        CatArt.TIRED_BATH_SCARF;
            };
            case DOG -> switch (uiScene) {
                case IDLE -> DogArt.IDLE;
                case FEED -> DogArt.FEED;
                case PLAY -> DogArt.PLAY;
                case SLEEP -> DogArt.SLEEP;
                case WAKE -> DogArt.IDLE;
                case SICK -> DogArt.SICK;
                case HUNGRY -> DogArt.HUNGRY;
                case TIRED -> DogArt.TIRED;
                case HEAL ->  DogArt.HEAL;
                case BOW ->  DogArt.BOW;
                case SCARF ->  DogArt.SCARF;
                case BATH ->  DogArt.BATH;
                case BATH_SCARF ->  DogArt.BATH_SCARF;
                case BATH_BOW ->  DogArt.BATH_BOW;
                case FEED_BOW ->   DogArt.FEED_BOW;
                case FEED_BATH ->    DogArt.FEED_BATH;
                case FEED_SCARF ->    DogArt.FEED_SCARF;
                case FEED_BATH_BOW -> DogArt.FEED_BATH_BOW;
                case FEED_BATH_SCARF ->     DogArt.FEED_BATH_SCARF;
                case PLAY_BATH ->     DogArt.PLAY_BATH;
                case PLAY_SCARF ->    DogArt.PLAY_SCARF;
                case PLAY_BOW ->     DogArt.PLAY_BOW;
                case PLAY_BATH_BOW ->     DogArt.PLAY_BATH_BOW;
                case PLAY_BATH_SCARF ->     DogArt.PLAY_BATH_SCARF;
                case HEAL_BOW ->      DogArt.HEAL_BOW;
                case HEAL_SCARF ->    DogArt.HEAL_SCARF;
                case HEAL_BATH ->     DogArt.HEAL_BATH;
                case HEAL_BATH_BOW ->     DogArt.HEAL_BATH_BOW;
                case HEAL_BATH_SCARF ->     DogArt.HEAL_BATH_SCARF;
                case SICK_BOW ->    DogArt.SICK_BOW;
                case SICK_BATH ->   DogArt.SICK_BATH;
                case SICK_SCARF ->  DogArt.SICK_SCARF;
                case SICK_BATH_BOW ->   DogArt.SICK_BATH_BOW;
                case SICK_BATH_SCARF -> DogArt.SICK_BATH_SCARF;
                case SLEEP_BOW ->     DogArt.SLEEP_BOW;
                case SLEEP_SCARF ->   DogArt.SLEEP_SCARF;
                case SLEEP_BATH ->      DogArt.SLEEP_BATH;
                case SLEEP_BATH_BOW ->      DogArt.SLEEP_BATH_BOW;
                case SLEEP_BATH_SCARF ->     DogArt.SLEEP_BATH_SCARF;
                case HUNGRY_BOW ->      DogArt.HUNGRY_BOW;
                case HUNGRY_BATH ->       DogArt.HUNGRY_BATH;
                case HUNGRY_SCARF ->      DogArt.HUNGRY_SCARF;
                case HUNGRY_BATH_BOW ->      DogArt.HUNGRY_BATH_BOW;
                case HUNGRY_BATH_SCARF ->       DogArt.HUNGRY_BATH_SCARF;
                case TIRED_BOW ->      DogArt.TIRED_BOW;
                case TIRED_BATH ->      DogArt.TIRED_BATH;
                case TIRED_SCARF ->       DogArt.TIRED_SCARF;
                case TIRED_BATH_BOW ->       DogArt.TIRED_BATH_BOW;
                case TIRED_BATH_SCARF ->        DogArt.TIRED_BATH_SCARF;
            };

            case HAMSTER -> switch (uiScene) {
                case IDLE -> HamsterArt.IDLE;
                case FEED -> HamsterArt.FEED;
                case PLAY -> HamsterArt.PLAY;
                case SLEEP -> HamsterArt.SLEEP;
                case WAKE -> HamsterArt.IDLE;
                case SICK -> HamsterArt.SICK;
                case HUNGRY -> HamsterArt.HUNGRY;
                case TIRED -> HamsterArt.TIRED;
                case HEAL -> HamsterArt.HEAL;
                case BOW -> HamsterArt.BOW;
                case SCARF -> HamsterArt.SCARF;
                case BATH -> HamsterArt.BATH;
                case BATH_SCARF -> HamsterArt.BATH_SCARF;
                case BATH_BOW ->  HamsterArt.BATH_BOW;
                case FEED_BOW ->   HamsterArt.FEED_BOW;
                case FEED_BATH ->    HamsterArt.FEED_BATH;
                case FEED_SCARF ->    HamsterArt.FEED_SCARF;
                case FEED_BATH_BOW ->     HamsterArt.FEED_BATH_BOW;
                case FEED_BATH_SCARF ->     HamsterArt.FEED_BATH_SCARF;
                case PLAY_BATH ->     HamsterArt.PLAY_BATH;
                case PLAY_SCARF ->    HamsterArt.PLAY_SCARF;
                case PLAY_BOW ->     HamsterArt.PLAY_BOW;
                case PLAY_BATH_BOW ->     HamsterArt.PLAY_BATH_BOW;
                case PLAY_BATH_SCARF ->     HamsterArt.PLAY_BATH_SCARF;
                case HEAL_BOW ->      HamsterArt.HEAL_BOW;
                case HEAL_SCARF ->    HamsterArt.HEAL_SCARF;
                case HEAL_BATH ->     HamsterArt.HEAL_BATH;
                case HEAL_BATH_BOW ->     HamsterArt.HEAL_BATH_BOW;
                case HEAL_BATH_SCARF ->     HamsterArt.HEAL_BATH_SCARF;
                case SICK_BOW ->    HamsterArt.SICK_BOW;
                case SICK_BATH ->   HamsterArt.SICK_BATH;
                case SICK_SCARF ->  HamsterArt.SICK_SCARF;
                case SICK_BATH_BOW ->   HamsterArt.SICK_BATH_BOW;
                case SICK_BATH_SCARF -> HamsterArt.SICK_BATH_SCARF;
                case SLEEP_BOW ->     HamsterArt.SLEEP_BOW;
                case SLEEP_SCARF ->   HamsterArt.SLEEP_SCARF;
                case SLEEP_BATH ->      HamsterArt.SLEEP_BATH;
                case SLEEP_BATH_BOW ->      HamsterArt.SLEEP_BATH_BOW;
                case SLEEP_BATH_SCARF ->     HamsterArt.SLEEP_BATH_SCARF;
                case HUNGRY_BOW ->      HamsterArt.HUNGRY_BOW;
                case HUNGRY_BATH ->       HamsterArt.HUNGRY_BATH;
                case HUNGRY_SCARF ->      HamsterArt.HUNGRY_SCARF;
                case HUNGRY_BATH_BOW ->      HamsterArt.HUNGRY_BATH_BOW;
                case HUNGRY_BATH_SCARF ->       HamsterArt.HUNGRY_BATH_SCARF;
                case TIRED_BOW ->      HamsterArt.TIRED_BOW;
                case TIRED_BATH ->      HamsterArt.TIRED_BATH;
                case TIRED_SCARF ->       HamsterArt.TIRED_SCARF;
                case TIRED_BATH_BOW ->       HamsterArt.TIRED_BATH_BOW;
                case TIRED_BATH_SCARF ->        HamsterArt.TIRED_BATH_SCARF;
            };
        };
    }
}
