package ui;

public enum UiScene {
    IDLE, FEED, PLAY, SLEEP, WAKE, SICK, HUNGRY, TIRED, HEAL, BOW, BATH, SCARF, BATH_BOW, BATH_SCARF,
    FEED_BATH, FEED_BOW, FEED_SCARF, FEED_BATH_BOW, FEED_BATH_SCARF,
    PLAY_BATH, PLAY_BOW, PLAY_SCARF, PLAY_BATH_BOW, PLAY_BATH_SCARF,
    SLEEP_BATH, SLEEP_BOW, SLEEP_SCARF, SLEEP_BATH_BOW, SLEEP_BATH_SCARF,
    SICK_BATH, SICK_BOW, SICK_SCARF, SICK_BATH_BOW, SICK_BATH_SCARF,
    HUNGRY_BATH, HUNGRY_BOW, HUNGRY_SCARF, HUNGRY_BATH_BOW, HUNGRY_BATH_SCARF,
    TIRED_BATH, TIRED_BOW, TIRED_SCARF, TIRED_BATH_BOW, TIRED_BATH_SCARF,
    HEAL_BATH, HEAL_BOW, HEAL_SCARF, HEAL_BATH_BOW, HEAL_BATH_SCARF,
}
